spring:
  profiles:
    active: dev
  thymeleaf:
    cache: false
    prefix: classpath:/static/
    suffix: .html
  jackson:
    # date-format: yyyy/MM/dd HH:mm:ss
    date-format: yyyy-MM-dd
    # 解决相差8小时问题
    time-zone: GMT+8
#  mvc:
#    date-format: yyyy-MM-dd


## mybatis数据源
mybatis:
  mapper-locations: classpath:mapper/*.xml #这里是mapper的配置文件
  # 这里是实体类的包 添加这个配置后就不用在mapper.xml配置文件中aliases了
  type-aliases-package: com.thd.springboottest.standardcode.entity
  configuration:
    map-underscore-to-camel-case: true # 驼峰属性与数据库字段下划线自动转换


logging:
  config: classpath:config/logback-spring.xml
  path: D:/deleteme/logback
  # mybatis log output
#  level:
#    com.thd.springboottest.standardcode.dao: debug # 输出mybatis的sql 和 参数



---
spring:
  profiles: dev
  application:
    name: thd - springboot standard code - dev
---
spring:
  profiles: test
  application:
    name: thd - springboot standard code - test

---
spring:
  profiles: prod
  application:
    name: thd - springboot standard code - prod