#debug: true



spring:
  jackson:
    # 对日期类型的序列化(服务端->客户端)
    # date-format: yyyy/MM/dd HH:mm:ss
    date-format: yyyy-MM-dd HH:mm:ss
    # 解决相差8小时问题
    time-zone: GMT+8
  # mvc:
    # 对日期类型的格式化(客户端->服务端)
    # date-format: yyyy-MM-dd
server:
  port: 8899
  servlet:
    context-path: /thd
#spring.mvc.view.prefix= /WEB-INF/pages/
#spring.mvc.view.suffix= .jsp