debug: true

#trace=true
# 打开actuator 所有端点
management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 8899
  servlet:
    context-path: /thd
#spring.mvc.view.prefix= /WEB-INF/pages/
#spring.mvc.view.suffix= .jsp


spring:
  redis:
    host: 127.0.0.1
    port: 6379
    #密码
    #password: 123456
    # 连接超时时间（毫秒）
    timeout: 10000
    #redis配置结束
    block-when-exhausted: true
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 1024
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 10000
        # 连接池中的最大空闲连接
        max-idle: 200
        # 连接池中的最小空闲连接
        min-idle: 10



